import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :my_system, MySystemWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  https: [
    port: 443,
    cipher_suite: :strong,
    otp_app: :my_system,
    keyfile: "/etc/letsencrypt/live/dcon-elixir.ftes.de/privkey.pem",
    certfile: "/etc/letsencrypt/live/dcon-elixir.ftes.de/cert.pem"
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
